iterative/PyDrive2

- pydrive2/files.py
- setup.py
First step to fix https://github.com/iterative/dvc/issues/3215 . More context is here - https://stackoverflow.com/a/59850170/298182
Step needed to fix `gdrive` dependencies in the DVC core repo, specifically these lines https://github.com/iterative/dvc/blob/master/setup.py#L87-L89
@efiop was you able to run tests/CI/stylers for this repo?
> Fix dependencies

- pydrive2/files.py
Deprecated `includeItemsFromAllDrives`, `includeTeamDriveItems` are updated with actual params to support Teamdrives.
`corpora` and optional `driveId` are supposed to be set at user's side.
> Update deprecated params to support Teamdrives

- setup.py
pyOpenSSL library should be available to enable p12 key files support (used to auth into Google Service accounts)
> Add pyOpenSSL dependency

- pydrive2/files.py
We rely on analyzing HTTPError cause in all API calls to retry. This is the only one (but very important - download), that was not using HTTPError, but a string due to some difference in the way it is called in code.
It affects DVC pull retrying properly when it hits user limits when we deal with large number of files.
> Use HTTPError as cause for file download

- pydrive2/auth.py
The http.redirect_codes attribute does not exist in old versions of httplib2.
> don't set http.redirect_codes if the attr doesn't exist

- pydrive2/files.py
- pydrive2/test/test_file.py
- pydrive2/test/test_util.py
- reference: https://developers.google.com/drive/api/v2/manage-downloads
- reference: https://developers.google.com/drive/api/v2/mime-types
And the (`pydrive2`) docstrings did say:
> `:returns: str -- utf-8 decoded content of the file`
And again, it (`httplib2`) said:
> `The return value is [...] a string that contains the response entity body.`
And the devs did shudder. There was wailing in the North and South. There was gnashing of teeth in the East and West.
And then one brave dev, in a quavering voice, spake thusly:
> Let there be no more in-memory downloads. Let the files stream until the hard drives overfloweth. Let RAM be ignored, and let us answer the call to progress.
- fixes #28
- related #20
- closes #29
> file.GetContentFile: stream to disk, add callback

- pydrive2/files.py
- fixes #31
Odd that there are no tests which picked up on this.
> files: fix auth for GetContentFile

- pydrive2/files.py
- pydrive2/test/test_file.py
Add authentication test
- continues #32
- prevents #31
> test authentication

- pydrive2/files.py
- pydrive2/test/test_file.py
+ [x] add `mimetype`
+ [x] add `encoding`
+ [x] add `__iter__` to make it easier to wrap à la https://github.com/iterative/dvc/blob/516d82e41107438756797611bbb15614cd4d989f/dvc/utils/http.py#L66
+ [x] add `remove_bom`
- fixes #38
> add files.GetContentIOBuffer

- pydrive2/files.py
Added the optional custom chunksize to the GetContentFile method.
Worked fine in my tests (I just forgot to init colorama in my callback, so it printed `?[2A` instead of printing the progressbar in the same line)
> Added a custom chunksize to the GetContentFile method.

- setup.py
There was a recent release 1.12.0 which broke because of its dependency with `six`,
and there has been another patch update `1.12.1` which fixes that. I could have just forbidden
`1.12.0`, but didn't trust other versions and tried to just use the latest version.
Recent release with the fix: https://github.com/googleapis/google-api-python-client/releases/tag/v1.12.1
> bump google-api-python-client version to the latest

- pydrive2/files.py
- pydrive2/test/test_file.py
https://github.com/iterative/dvc/issues/4286
> gdrive: download empty file

- pydrive2/files.py
- setup.py
https://github.com/googleapis/google-api-python-client/pull/1070 is now
merged, so we can get rid of our hack
https://github.com/iterative/PyDrive2/pull/48
Fixes https://github.com/iterative/PyDrive2/issues/59
> gdrive: remove empty file hack

- docs/quickstart.rst
Title cased section headings, added more description to section on get_id_of_title, changed some language to be clearer.
> Update quickstart documentation

- pydrive2/auth.py
seems like the default `access_type` is `offline` so I added this line to make sure that the default behavior does not get the refresh token
> a fix for access_type

- setup.py
It seems like pydrive is incompatible with google-api-python-cleint>=2.0 (which is actually yanked on PyPI), https://stackoverflow.com/questions/66477468/data-version-control-with-google-drive-remote-googleapiclient-errors-unknownap
> setup: restrict the upperbound of google-api-python-client

- pydrive2/auth.py
- pydrive2/test/settings/default.yaml
- pydrive2/test/settings/test_oauth_test_07.yaml
- pydrive2/test/test_oauth.py
- pydrive2/test/test_util.py
Redundantly introduced in #81, and the cause of some downstream issues. Removing per #96
> auth: drop json credentials backend

- pydrive2/files.py
- pydrive2/test/test_file.py
There is a bug in the current implementation (, is missing between two fields in the _ALL_FIELDS list).
This is an attempt to simplify the logic by using * instead of _ALL_FIELDS + add tests to cover this and check presence some of the fields (e.g. permissions that are not fetched by default if * is not provided).
> Fixes 103: fix and simplify fetch all metadata logic

- pydrive2/fs/spec.py
- pydrive2/test/test_fs.py
Closes https://github.com/iterative/PyDrive2/issues/136
> fs.get_file: add callback support

- docs/filemanagement.rst
previously links were like: https://docs.iterative.ai/PyDrive2/filelist/pydrive2.html#pydrive2.files.GoogleDriveFile which resulted in 404 error
> Fix links to /pydrive2/

- .pre-commit-config.yaml
- pydrive2/auth.py
- pydrive2/test/README.rst
- pydrive2/test/settings/test_oauth_test_08.yaml
- pydrive2/test/settings/test_oauth_test_09.yaml
- pydrive2/test/test_oauth.py
- setup.py
Fixes #163 
The reason for the bug in #163 is here:
https://github.com/iterative/PyDrive2/blob/master/pydrive2/auth.py#L396-L398
The problem is that every time any thread runs `SaveCredentialsFile` when token is being refreshed it sets the new Storage object, each storage object defines the `Lock` that is being used later for `put`, `get`, and other operations that are being done with the storage (clearly we don't want multiple threads writing and / or reading the same file again).
The following situation was possible:
T1 - acquires lock A from the Storage A
T2 - waits to acquire the same lock A
T1 - saves credentials, releases lock A, and updates Storage A to Storage B and the same happens with lock, now it's lock B
(it's already not thread safe since T1 now can do some stuff in parallel …
> Fix 163: make credentials save/load thread safe

- pydrive2/fs/spec.py
As discussed in #191, to make `GDriveFileSystem` compatible with google docs / sheet files the checksum in the metadata need to be optional.
I tried to run the tests in `test_fs.py` and it's all green.
> make checksum optional in GDriveFileSystem

- pydrive2/auth.py
This allows programmatic use without having to create a temporary file.
> auth: add client_creds_dict

- pydrive2/auth.py
This allows programmatic use without having to create a settings file
or barbarically modifying `GoogleAuth.DEFAULT_SETTINGS`.
> auth: support passing settings dict to GoogleAuth

- docs/oauth.rst
- pydrive2/auth.py
- pydrive2/test/test_oauth.py
Allows not to save anything to disk, which is useful overall but especially
useful when working with env vars, which could be sensitive so saving their
value to disk is undesirable.
> auth: add dictionary storage

- docs/oauth.rst
- pydrive2/auth.py
- pydrive2/settings.py
- pydrive2/test/test_oauth.py
`client_creds_dict` was introduced in experimental mode before (a few days back) and wasn't documented. Renaming it into `client_json_dict` to be consistent with other options.
Introducing `client_json` for convenience to syncronize with oauth2 storage options so that users can use either dict or json and not be forced to use both of them when authenticating.
> auth: add client_json and client_json_dict

- .github/workflows/test.yml
- pydrive2/auth.py
- pydrive2/test/test_oauth.py
If `client_user_email` is not specified - it will trigger `LoadServiceConfigSettings` call during `ServiceAuth`, which will raise an exception because it doesn't see neither `json` nor `pkcs12` keyfile path.
> auth: service: don't forget to load json configs

- README.rst
- docs/fsspec.rst
- docs/index.rst
- pydrive2/fs/spec.py
- pydrive2/test/test_fs.py
- setup.py
Compared to how we were using it in dvc before:
1) doesn't require/accept `tmp_dir` at all, caches creds in
`appdirs("pydrive2fs", appauthor=False)`.
2) caching is per `client_id`, so no risk of using mismatched client_id and
cached creds. If user supplies a `profile`(defaults to `default`) - we'll
also cache it by `profile` to support multiple google users using the same
`client_id`.
3) renamed `service_account_json_file_path` into `client_json_file_path` for
consistency.
4) renamed `service_account_user_email` into `client_user_email` for
consistency.
Other than that, this is mostly old code.
Fixes https://github.com/iterative/PyDrive2/issues/193
> fs: simplify auth

- pydrive2/fs/spec.py
These are really not meant to be public and we shouldn't expose them here or
in auto-generated docs.
> fs: hide gdrive_* methods

- docs/filemanagement.rst
- docs/fsspec.rst
- pydrive2/files.py
- pydrive2/fs/spec.py
Related #62
Pre-requisite for https://github.com/iterative/dvc/issues/7832
> fs: add acknowledge_abuse parameter

- pyproject.toml
- setup.py
Avoids having us to bump the version manually.
> build: add setuptools_scm

- .github/workflows/publish.yml
See https://github.com/pypa/gh-action-pypi-publish#-master-branch-sunset-.
> [skip ci]: use gh-action-pypi-publish@release/v1

- docs/filemanagement.rst
- docs/oauth.rst
Recently I needed to use Google Drive with Python so this library was very useful but I needed more help for my uses cases that arent the simplest or common, I want to extend the documentation to make more easy its use for future users.
- Oauth: with google service account
- File management: Get files by complex queries with [q parameters](https://developers.google.com/drive/api/guides/search-files#examples)
- File management: Upload data as bytes in memory buffer
- File management: Upload file to specific folder
See #230 for more insight on the motivation for this.
> add more documentation to auth and file management

- .pre-commit-config.yaml
- pydrive2/__pyinstaller/__init__.py
- pydrive2/__pyinstaller/hook-googleapiclient.py
- pydrive2/__pyinstaller/test_hook-googleapiclient.py
- setup.py
Adds package level pyinstaller hooks so that any downstream package using pydrive2 + pyinstaller does not need to define their own hooks for the google client APIs
see details in the pyinstaller docs: https://pyinstaller.org/en/stable/hooks.html#providing-pyinstaller-hooks-with-your-package)
related:
https://github.com/iterative/PyDrive2/issues/197
https://github.com/iterative/dvc/issues/7949
> pyinstaller: add package hooks

- pydrive2/fs/spec.py
Fixes #256 
Some files (I think older Google docs, sheets, etc - prior to ~May 2022) don't have size fields. This enables compatibility with these files.
> fix/256(fsspec): size can be None for drive files

- pydrive2/apiattr.py
This code:
```
self.auth.service.files()
.insert(**param)
.execute(http=self.http)
```
That is used here https://github.com/iterative/PyDrive2/blob/main/pydrive2/files.py#L678-L680
Started returning metadata object with download URL like this:
`'downloadUrl': 'https://www.googleapis.com/drive/v2/files/16USPEjsYg7WEL3J62p4N4TRE5_ZMr3SW?alt=media&source=downloadUrl'`
That was breaking the download content later that is relying on the `downloadUrl` here:
https://github.com/iterative/PyDrive2/blob/main/pydrive2/files.py#L476
And it's visible in the tests, e.g. here: https://github.com/iterative/PyDrive2/pull/269
I hope it's a temporary patch and it will be fixed upstream soon. It might be related to the deprecated v2 of the API which we don't have capacity at the moment to fix :(
> fix(upload): returns broken `downloadUrl`

- pydrive2/fs/spec.py
Similar to https://github.com/iterative/dvc/pull/9279
Fixes https://github.com/iterative/dvc/issues/9312
> fs: use itertools.chain.from_iterable instead of funcy.py3.cat

- pydrive2/files.py
- pydrive2/test/test_file.py
Fixes #272 
I don't see a good reason to keep this behavior. Magic that is not consistent with other `Set*Content` methods. 
Downside of this approach is that it breaks the compatibility a bit. Let's see how it goes, we might release a major / minor version.
--------
TODO:
> fix(upload/272): don't magically set filename on set file content

- docs/filemanagement.rst
- pydrive2/files.py
- pydrive2/test/test_file.py
Fixes #272 . Followup after #273 . 
Trying a bit less dramatic change. It should not be breaking backward compatibility and is fixing #272 as a regression.
> Set content picks default title/mime if file is created for the first time

- pydrive2/auth.py
Currently, there doesn't seem to be a way to authenticate using the LocalWebserverAuth flow while running inside a local docker container because Docker's port forwarding doesn't help with localhost-only-bound ports. This PR adds a `bind_addr` parameter, intended for you to pass `"0.0.0.0"` to it, basically providing the same functionality as described in https://github.com/googleapis/google-auth-library-python-oauthlib/pull/202. 
Relatedly, the CommandlineAuth flow seems to now be completely blocked by Google, but I didn't touch that in this PR.
> Add bind_addr parameter to LocalWebserverAuth

- .github/workflows/test.yml
See https://github.com/actions/setup-python/issues/682 and https://github.com/fsspec/filesystem_spec/pull/1295.
> ci: temporarily pin to Python 3.7.16

- pydrive2/fs/spec.py
- pydrive2/test/test_fs.py
Per https://github.com/iterative/dvc-gdrive/issues/29
> GDriveFileSystem: Raise `FIleNotFoundError` on `ls`.

- pydrive2/fs/spec.py
GDriveFileSystem was previously caching dir ids of root, and was using those on `fs.find()`.
This worked well when the remote cache was at the root, but now since dvc uses `/files/md5/` by default, the dir ids are no longer in the cache and `find` ends up returning an empty list.
This PR checks if the path is cached, and if not, it caches the ID of the path.
Tests passes for dvc in https://github.com/iterative/dvc-gdrive/pull/28
> fs.find: cache path ids

- pydrive2/files.py
- pydrive2/settings.py
Looks like this was an anti pattern that stuck around from some early days.
Fixes https://github.com/iterative/dvc-gdrive/issues/31
> pydrive2: use isinstance() instead of type()

- .github/workflows/publish.yml
https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers#using-trusted-publishing-with-github-actions
> Migrate from PyPI tokens to Trusted Publishers

- .github/workflows/publish.yml
Similar to how we do in dvc.
https://github.com/iterative/dvc/blob/7c898cfad707f973f8318182c99e52285bc49bff/.github/workflows/build.yaml#L76
> prevent tags from publishing without creating releases

- pydrive2/fs/spec.py
To mitigate https://github.com/iterative/dvc-gdrive/issues/38
It removes the pre-caching logic of `root/00`, `root/01`, .... `root/ff` DVC cache specific directories. It existed to optimize number of API calls, specifically when we use `exists` calls on the DVC transfer side and we have to do 2x calls in some simple scenarios. It's slower and expensive.
With this PR cache is becoming more general (e.g. we cache all directories we create). It makes sense for `fsspec`. To make it clear - the whole `fsspec` implementation in general case is still very broken and it'll be addressed step by step eventually.
The optimization can be turned back on with ad additional "pre_cache_path" argument. But let's do it after we fix the basic GDrive scenario with this one.
> fix(fs): remove DVC-specific broken cache optimization

- pydrive2/fs/spec.py
Caching mechanics was broken in certain scenarios and affected DVC tremendously. Before we were assuming pre-cached paths for `00`, `01` .... `ff` in DVC. It got broken during DVC 3.0 release, and then got removed completely because of this. Now it's not the case and DVC was kept asking for `files`, `files\md5`, etc - all those IDs again and again and again on `dvc pull`. Pretty much every object could be 3x slower to download.
Among other things, I checked that `dvc pull` works now even with duplicated root dirs in DVC remote.
Still need to self review this, and next see if we can add tests for all of this. It keeps biting us. Caching is non trivial and we cant be losing the knowledge as we go, every time coming back to fix it after users complain.
> fix(fs): add dirs caching, make it a bit more robust

- pydrive2/auth.py
- pydrive2/test/test_oauth.py
Closes https://github.com/iterative/PyDrive2/issues/319
Adds `GDRIVE_NON_INTERACTIVE` variable so that `LocalWebserverAuth` raises `pydrive2.auth.AuthenticationError` if it's called.
This is might be handy in any server side / automated environment where we can't really expect anyone interacting with a browser.
> feat(auth): add GDRIVE_NON_INTERACTIVE to avoid launching browser

- pydrive2/fs/spec.py
- pydrive2/test/test_fs.py
- pydrive2/test/test_util.py
Tests for the recent PR regressions:
https://github.com/iterative/PyDrive2/pull/322
https://github.com/iterative/PyDrive2/pull/321
Also seems that https://github.com/iterative/PyDrive2/issues/229 is fixed now. This PR also covers a basic test for it. @simone-viozzi please confirm if / when you have time.
Closes https://github.com/iterative/PyDrive2/issues/229
> chore(fs): add tests to cover recent PRs

- docs/filemanagement.rst
Currently the `GetContentString()` link on this [docs page](https://docs.iterative.ai/PyDrive2/filemanagement/) links incorrectly to: https://docs.iterative.ai/PyDrive2/filemanagement/PyDrive2/pydrive2/#pydrive2.files.GoogleDriveFile.GetContentString
> Fix broken `GetContentString()` docs link

- .github/workflows/test.yml
macos-11 is beting deprecated, Python 3.8 is coming to and end, and Python 3.12 is stable now.
> try to update to latest runners

- pydrive2/fs/spec.py
Fixes #359 
It seems we had names of arguments (order) wrong in the `get_file` implementation. `rpath` stands for remote path should come first, `lpath` - second. I don't see (need to double check) if we do any `root` asserts on the `lpath` if it's passed in the correct order / place.
> fix(fs): rename get file args to fsspec spec

- setup.py
Mitigates https://github.com/iterative/PyDrive2/issues/361
As a quick fix pin pyopenssl for now.
We need to migrate out of https://github.com/googleapis/oauth2client that is long time deprecated and is causing all these issues. Most likely there were already draft PRs for this. If someone from the community can help with that - it would be amazing.
> fix(deps): pin pyopenssl due to incompatible changes

- setup.py
pyopenssl<24.3.0 is not compatible with cryptography<44. So, limiting them so that newer version of cryptography does not get installed with older version of pyopenssl.
Related: #361.
> set upper bound for cryptography
